config/routes.rb
Geezeo::Application.routes.draw do

  resources :accounts, :only => [:index, :show] do
    member do
      get "transactions"
    end
  end
  
  resources :transactions, :only => [:index]

  root :to => 'accounts#index'

end

app/models/account.rb
class Account 
  
  attr_accessor :id, :name, :balance, :reference_id, :aggregation_type,
                :state, :harvest_updated_at, :account_type, :fi, :user


  def initialize(attrs={})
    attrs.each{|k,v| send("#{k}=",v)}
    @transactions = []
  end

  def ==(other_account)
    other_account.id == self.id
  end

  def transactions(page=1)
    @transactions[page] ||= TransactionList.new(geezeo_api.transactions_for_user_account(self.user, self, page))
  end

  def balance=(attr)
    @balance = Float(attr)
  end

  def to_param
    self.id
  end

  def all_transactions
    TransactionList.new(geezeo_api.all_transactions_for_user_account(self.user, self))
  end

  private

  def geezeo_api
    @geezeo_api ||= GeezeoApi.new(AppConfig[:api_key])
  end

end

app/models/transaction.rb
class Transaction < OpenStruct

  def debit?
    transaction_type == "Debit"
  end

  def credit?
    transaction_type == "Credit"
  end

  def <=>(transaction)
    val = self.time <=> transaction.time
    if val == 0
      val = self.memo <=> transaction.memo
    end
    val
  end

  def date
    time.strftime("%m-%d-%Y")
  end

  def time
    Time.parse(self.posted_at)
  end
end

app/models/transaction_list.rb
class TransactionList

  include Enumerable

  attr_reader :current_page, :total_pages

  def initialize(attrs)
    transactions = attrs[:transactions]
    pagination = attrs[:pagination]
    @transactions = transactions.map{|t| Transaction.new(t)}.sort.reverse
    @current_page = pagination["current_page"].to_i
    @total_pages = pagination["total_pages"].to_i
  end

  def each &block
    @transactions.each &block
  end

  def to_csv
    CSV.generate do |csv|
      cols = ["id", "transaction_type", "balance", "memo"]
      csv << cols
      self.each do |tr|                
        csv << [tr.id, tr.transaction_type, tr.balance, tr.memo]
      end
    end
  end

end

app/models/user.rb
class User

  def id
    "nakort"
  end

  def accounts
    @accounts ||= geezeo_api.accounts_for_user(self).map{|ac| Account.new(ac.merge(:user => self))}
  end

  def find_account(id)
    accounts.find{|account| account.id == id}
  end

  def total_balance
    accounts.inject(0.0){|total, account| total + account.balance}
  end

  def transactions
    @transactions ||= TransactionList.new(geezeo_api.transactions_for_user(self))
  end

  private

  def geezeo_api
    @geezeo_api ||= GeezeoApi.new(AppConfig[:api_key])
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @accounts = current_user.accounts
  end

  def show
    @account = current_user.find_account(params[:id].to_i)
    @transactions = @account.transactions(params.fetch(:page, 1).to_i)
    @accounts = current_user.accounts
    @accounts.delete(@account)
  end

  def transactions
    account = current_user.find_account(params[:id].to_i)
    send_data(account.all_transactions.to_csv, 
              :type => 'text/csv; charset=utf-8; header=present', 
              :filename => "transactions-#{Time.now.to_date.to_s}.csv")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery
  helper_method :current_user

  def current_user
    @current_user ||= User.new
  end

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    send_data(current_user.transactions.to_csv, 
              :type => 'text/csv; charset=utf-8; header=present', 
              :filename => "transactions-#{Time.now.to_date.to_s}.csv")
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_credit_transaction.html.erb
<tr>
  <td>
    <%= transaction.date %>
  </td>
  <td>
    <%= transaction.memo%>
  </td>
  <td>
    <%= transaction.balance %>
  </td>
  <td>
  </td>
</tr>

app/views/accounts/_debit_transaction.html.erb
<tr>
  <td>
    <%= transaction.date %>
  </td>
  <td>
    <%= transaction.memo%>
  </td>
  <td>
  </td>
  <td>
    <%= transaction.balance %>
  </td>
</tr>

app/views/accounts/index.html.erb
<h2>
  Accounts
</h2>

<div class="row">
  <div class="span4">
    <table class="table">
      <thead>
        <td>
          Name
        </td>
        <td>
          Balance
        </td>
      </thead>
      <tbody>
        <% @accounts.each do |account| %>
          <tr>
            <td>
              <%= link_to account.name, account_path(account) %>
            </td>
            <td>
              <%= account.balance %>
            </td>
          </tr>
        <% end %>
        <tr>
          <td>Total Balance:</td>
          <td> <%= current_user.total_balance %> </td>
        </tr>
      </tbody>
    </table>
    <%= link_to "Download CSV of all accounts transactions", transactions_path(@account) %>
  </div>
</div>

app/views/accounts/show.html.erb
<h2>
  Transactions for
  <div class="btn-group">
    <%= link_to @account.name, account_path(@account), :class=> "btn btn-primary" %>
    <a class="btn btn-primary dropdown-toggle" data-toggle="dropdown" href="#"><span class="caret"></span></a>
    <ul class="dropdown-menu">
      <% @accounts.each do |account|%>
        <li><%= link_to account.name, account_path(account) %></li>
      <% end %>
    </ul>
  </div>
</h2>


<div class="row">
  <div class="span7">
    <table class="table">
      <thead>
        <td>
          Date
        </td>
        <td>
          Description
        </td>
        <td>
          Deposits/Credits
        </td>
        <td>
          Withdrawals/Debits
        </td>
      </thead>
      <tbody>
        <% @transactions.each do |transaction| %>
          <%= render "#{transaction.transaction_type.downcase}_transaction", :transaction => transaction %>
        <% end %>
      </tbody>
    </table>
    <div class="pagination">
      <ul>
        <% @transactions.total_pages.times do |i| %>
          <% i = i + 1 %>
          <li class="<%= @transactions.current_page == i ? 'active' : '' %>">
            <%= link_to i.to_s, account_path(@account, :page => i) %>
          </li>
        <% end %>
      </ul>
    </div>
    <%= link_to "Download CSV", transactions_account_path(@account) %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Geezeo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>